// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("httplogreceiver")
	ScopeName = "github.com/NoirAI/noirai-otel-collector/receiver/httplogreceiver"
)

const (
	LogsStability = component.StabilityLevelAlpha
)
