// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("noiraiclickhousemetrics")
	ScopeName = "github.com/no1rstack/noirai-otel-collector/exporter/noiraiclickhousemetrics"
)

const (
	MetricsStability = component.StabilityLevelBeta
)
