// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("signozspanmetrics")
	ScopeName = "github.com/no1rstack/noirai-otel-collector/processor/signozspanmetricsprocessor"
)

const (
	TracesStability = component.StabilityLevelBeta
)
