// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("noiraispanmetrics")
	ScopeName = "github.com/NoirAI/noirai-otel-collector/processor/noiraispanmetricsprocessor"
)

const (
	TracesStability = component.StabilityLevelBeta
)
