// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("noiraijsontypeexporter")
	ScopeName = "github.com/no1rstack/noirai-otel-collector/exporter/jsontypeexporter"
)

const (
	LogsStability = component.StabilityLevelAlpha
)
