// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("noirai_health_check")
	ScopeName = "github.com/NoirAI/noirai-otel-collector/extension/healthcheckextension"
)

const (
	ExtensionStability = component.StabilityLevelBeta
)
