// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("noirailogspipeline")
	ScopeName = "github.com/NoirAI/noirai-otel-collector/processor/noirailogspipelineprocessor"
)

const (
	LogsStability = component.StabilityLevelBeta
)
