// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("noiraimeter")
	ScopeName = "github.com/no1rstack/noirai-otel-collector/connectors/noiraimeterconnector"
)

const (
	TracesToMetricsStability  = component.StabilityLevelBeta
	MetricsToMetricsStability = component.StabilityLevelBeta
	LogsToMetricsStability    = component.StabilityLevelBeta
)
