// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("noiraiclickhousemeter")
	ScopeName = "github.com/NoirAI/noirai-otel-collector/exporter/noiraiclickhousemeter"
)

const (
	MetricsStability = component.StabilityLevelBeta
)
